name: Cart CI

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test: ## STEP-1 IN CI PIPELINE testing the application
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Run a One line test
        run: echo npm test

  docker: ## STEP-2 IN CI PIPELINE artifacting the application
    needs: test
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4
      - name: Docker Login for pusing image
        run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 444206648334.dkr.ecr.us-east-1.amazonaws.com
      - name: Docker Build
        run: docker build -t 444206648334.dkr.ecr.us-east-1.amazonaws.com/cart .
      - name: Docker Push
        run: docker push 444206648334.dkr.ecr.us-east-1.amazonaws.com/cart
